[package]
name = "uiuifree-normalize"
version = "0.1.0"
edition = "2021"
authors = ["uiuifree"]
description = ""
license = "MIT"
repository="https://github.com/uiuifree/uiuifree-normalize"


[dependencies]
unicode-jp = "0.4"
regex="1.1"
voca_rs="1.14"
lazy_static="1.4"
