[package]
name = "uiuifree-normalize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-jp = "0.4"
regex="1.1"
voca_rs="1.14"
lazy_static="1.4"
